/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `content_items` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Class` enum('Emergence\\CMS\\Item\\Album','Emergence\\CMS\\Item\\Embed','Emergence\\CMS\\Item\\Media','Emergence\\CMS\\Item\\RichText','Emergence\\CMS\\Item\\Text','Emergence\\CMS\\Item\\Markdown') NOT NULL,
  `Created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatorID` int(11) DEFAULT NULL,
  `Modified` timestamp NULL DEFAULT NULL,
  `ModifierID` int(10) unsigned DEFAULT NULL,
  `Title` varchar(255) DEFAULT NULL,
  `ContentID` int(10) unsigned NOT NULL,
  `AuthorID` int(10) unsigned NOT NULL,
  `Status` enum('Draft','Published','Hidden','Deleted') NOT NULL DEFAULT 'Published',
  `Order` int(10) unsigned DEFAULT NULL,
  `Data` text NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ContentID` (`ContentID`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `content_items` VALUES (1,'Emergence\\CMS\\Item\\Markdown','2017-09-05 17:09:44',1,'2017-09-05 17:09:45',1,NULL,1,1,'Published',1,'\"Hello world\"');
INSERT INTO `content_items` VALUES (2,'Emergence\\CMS\\Item\\Markdown','2017-09-05 17:10:03',1,'2017-09-05 17:10:03',1,NULL,2,1,'Published',1,'\"Hello world\"');
INSERT INTO `content_items` VALUES (3,'Emergence\\CMS\\Item\\Markdown','2017-09-06 17:50:08',23,'2017-09-06 19:52:38',23,NULL,3,23,'Published',1,'\"Donec massa elit, vulputate maximus dui vitae, bibendum aliquet lectus. Nulla porttitor tempor enim in scelerisque. Donec gravida eros ante, eget accumsan nisi suscipit ultrices. In sit amet sodales magna. Donec maximus magna id volutpat condimentum. Donec suscipit ac ante id lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\\n\\nInteger finibus leo eros, vel vehicula nisl semper et. Proin sed metus eleifend, elementum ligula id, posuere elit. Proin sed sagittis quam. Mauris ac orci tincidunt justo iaculis mattis at blandit magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur quis nisl blandit, eleifend purus non, molestie arcu. Aliquam erat volutpat. Nullam quis mauris eget leo euismod interdum ut id velit. Nunc et augue quis diam imperdiet viverra. Proin sollicitudin volutpat erat. Suspendisse eget justo vel elit mollis molestie dignissim eu tortor. Quisque quis lorem viverra, sagittis nisl non, pellentesque lectus. Nunc feugiat lacus at arcu mattis accumsan. Mauris iaculis posuere accumsan. Duis metus libero, semper at hendrerit eu, mollis sit amet lectus. Sed nec eros congue, rhoncus nunc ac, consectetur nulla.\\n\\nPhasellus efficitur arcu quis arcu sollicitudin mollis id ut dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec ultrices mattis varius. Donec et quam commodo, consectetur augue vitae, facilisis ligula. Praesent arcu arcu, scelerisque sed ultricies ac, pretium vitae mi. Vivamus non libero ac lorem faucibus molestie non quis purus. Duis tristique commodo lectus, nec dignissim purus lacinia nec. Mauris ornare sapien risus, eu consectetur mauris vehicula a. Cras bibendum enim vel lobortis dictum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean semper elit ut risus convallis, at pharetra est eleifend.\"');
INSERT INTO `content_items` VALUES (4,'Emergence\\CMS\\Item\\Markdown','2017-09-06 17:51:30',2,'2017-09-06 19:39:31',2,NULL,4,2,'Published',1,'\"Ut euismod tincidunt libero, sit amet iaculis ligula dictum in. Vestibulum rutrum auctor ante non convallis. Integer fringilla quis velit eget tempus. Vivamus ligula mi, ultricies vel viverra sed, lobortis id sem. Morbi in dui eu risus porttitor venenatis pellentesque id ligula. Aenean non commodo magna. Donec vel accumsan nibh. Duis lacus nisl, volutpat a iaculis et, tincidunt quis tortor. Phasellus sit amet elementum felis. Proin viverra egestas mauris. Aenean nec convallis lacus. Nullam egestas nulla ligula, sed aliquet lectus eleifend a. Nunc laoreet, urna a accumsan pharetra, leo odio consequat arcu, ut pulvinar eros turpis at ipsum.\\n\\nSed vel molestie justo, id sollicitudin velit. Maecenas volutpat massa quis urna eleifend porta. Duis mattis tincidunt ante nec placerat. Ut volutpat neque et mi elementum posuere. Ut sed augue posuere, volutpat neque a, pretium ante. Praesent at justo magna. Duis pellentesque dignissim turpis, at vulputate dolor. Vestibulum sagittis vestibulum tellus, vitae cursus leo pellentesque quis. Nunc euismod commodo tortor, eget efficitur ligula consequat auctor. Sed vehicula elit tempus lacus consectetur, et mollis turpis tempus. Integer accumsan lacinia suscipit.\"');
INSERT INTO `content_items` VALUES (5,'Emergence\\CMS\\Item\\Markdown','2017-09-06 19:10:02',23,'2017-09-06 19:37:22',23,NULL,5,23,'Published',1,'\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac dui ultricies, condimentum augue eu, consectetur nulla. Nulla eleifend consectetur nisi, at pretium lorem. Ut porttitor erat quam, ut vestibulum orci consequat ac. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla vehicula eros at odio dictum, id interdum libero malesuada. Morbi consequat erat et eros dapibus tempus. Nulla gravida lectus tellus, vel faucibus odio hendrerit in. Integer non turpis lorem. Donec imperdiet gravida erat, ac sodales odio blandit eu. Morbi ullamcorper vel velit at condimentum. In hac habitasse platea dictumst. Donec eget scelerisque tortor. In congue urna id felis placerat ultrices pellentesque ut libero.\"');
INSERT INTO `content_items` VALUES (6,'Emergence\\CMS\\Item\\Markdown','2017-09-06 19:20:23',2,'2017-09-06 19:38:38',2,NULL,6,2,'Published',1,'\"Maecenas neque diam, dignissim id nunc id, aliquam lobortis lorem. Nunc porttitor risus non ligula condimentum consectetur. Integer eget tortor fermentum, auctor metus sed, faucibus nisl. Vestibulum fermentum molestie quam, non viverra mi efficitur ac. Curabitur et vehicula leo. Duis lacus odio, tincidunt vel consectetur vel, porttitor ac diam. Sed in laoreet augue, id sodales dui. Praesent quis condimentum metus. Quisque odio nulla, sodales sit amet nisl id, ultrices porttitor nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\\n\\nPellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque eget lacus efficitur, feugiat risus nec, efficitur mi. Morbi iaculis dui ut nunc gravida, eget pretium ipsum cursus. Donec malesuada enim eros, nec vehicula mi cursus ut. Aliquam laoreet nisi id ante facilisis gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed eget odio a neque consectetur pretium eget at sapien. Nunc vel ornare metus. Suspendisse quam leo, finibus quis placerat et, accumsan eu turpis. Suspendisse non aliquet urna.\"');
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `history_content_items` (
  `RevisionID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID` int(10) unsigned NOT NULL,
  `Class` enum('Emergence\\CMS\\Item\\Album','Emergence\\CMS\\Item\\Embed','Emergence\\CMS\\Item\\Media','Emergence\\CMS\\Item\\RichText','Emergence\\CMS\\Item\\Text','Emergence\\CMS\\Item\\Markdown') NOT NULL,
  `Created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatorID` int(11) DEFAULT NULL,
  `Modified` timestamp NULL DEFAULT NULL,
  `ModifierID` int(10) unsigned DEFAULT NULL,
  `Title` varchar(255) DEFAULT NULL,
  `ContentID` int(10) unsigned NOT NULL,
  `AuthorID` int(10) unsigned NOT NULL,
  `Status` enum('Draft','Published','Hidden','Deleted') NOT NULL DEFAULT 'Published',
  `Order` int(10) unsigned DEFAULT NULL,
  `Data` text NOT NULL,
  PRIMARY KEY (`RevisionID`),
  KEY `ID` (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `history_content_items` VALUES (1,1,'Emergence\\CMS\\Item\\Markdown','2017-09-05 17:09:44',1,'2017-09-05 17:09:45',1,NULL,1,1,'Published',1,'\"Hello world\"');
INSERT INTO `history_content_items` VALUES (2,2,'Emergence\\CMS\\Item\\Markdown','2017-09-05 17:10:03',1,'2017-09-05 17:10:03',1,NULL,2,1,'Published',1,'\"Hello world\"');
INSERT INTO `history_content_items` VALUES (3,3,'Emergence\\CMS\\Item\\Markdown','2017-09-06 17:50:08',23,'2017-09-06 19:52:38',23,NULL,3,23,'Published',1,'\"Donec massa elit, vulputate maximus dui vitae, bibendum aliquet lectus. Nulla porttitor tempor enim in scelerisque. Donec gravida eros ante, eget accumsan nisi suscipit ultrices. In sit amet sodales magna. Donec maximus magna id volutpat condimentum. Donec suscipit ac ante id lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\\n\\nInteger finibus leo eros, vel vehicula nisl semper et. Proin sed metus eleifend, elementum ligula id, posuere elit. Proin sed sagittis quam. Mauris ac orci tincidunt justo iaculis mattis at blandit magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur quis nisl blandit, eleifend purus non, molestie arcu. Aliquam erat volutpat. Nullam quis mauris eget leo euismod interdum ut id velit. Nunc et augue quis diam imperdiet viverra. Proin sollicitudin volutpat erat. Suspendisse eget justo vel elit mollis molestie dignissim eu tortor. Quisque quis lorem viverra, sagittis nisl non, pellentesque lectus. Nunc feugiat lacus at arcu mattis accumsan. Mauris iaculis posuere accumsan. Duis metus libero, semper at hendrerit eu, mollis sit amet lectus. Sed nec eros congue, rhoncus nunc ac, consectetur nulla.\\n\\nPhasellus efficitur arcu quis arcu sollicitudin mollis id ut dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec ultrices mattis varius. Donec et quam commodo, consectetur augue vitae, facilisis ligula. Praesent arcu arcu, scelerisque sed ultricies ac, pretium vitae mi. Vivamus non libero ac lorem faucibus molestie non quis purus. Duis tristique commodo lectus, nec dignissim purus lacinia nec. Mauris ornare sapien risus, eu consectetur mauris vehicula a. Cras bibendum enim vel lobortis dictum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean semper elit ut risus convallis, at pharetra est eleifend.\"');
INSERT INTO `history_content_items` VALUES (4,4,'Emergence\\CMS\\Item\\Markdown','2017-09-06 17:51:30',2,'2017-09-06 19:39:31',2,NULL,4,2,'Published',1,'\"Ut euismod tincidunt libero, sit amet iaculis ligula dictum in. Vestibulum rutrum auctor ante non convallis. Integer fringilla quis velit eget tempus. Vivamus ligula mi, ultricies vel viverra sed, lobortis id sem. Morbi in dui eu risus porttitor venenatis pellentesque id ligula. Aenean non commodo magna. Donec vel accumsan nibh. Duis lacus nisl, volutpat a iaculis et, tincidunt quis tortor. Phasellus sit amet elementum felis. Proin viverra egestas mauris. Aenean nec convallis lacus. Nullam egestas nulla ligula, sed aliquet lectus eleifend a. Nunc laoreet, urna a accumsan pharetra, leo odio consequat arcu, ut pulvinar eros turpis at ipsum.\\n\\nSed vel molestie justo, id sollicitudin velit. Maecenas volutpat massa quis urna eleifend porta. Duis mattis tincidunt ante nec placerat. Ut volutpat neque et mi elementum posuere. Ut sed augue posuere, volutpat neque a, pretium ante. Praesent at justo magna. Duis pellentesque dignissim turpis, at vulputate dolor. Vestibulum sagittis vestibulum tellus, vitae cursus leo pellentesque quis. Nunc euismod commodo tortor, eget efficitur ligula consequat auctor. Sed vehicula elit tempus lacus consectetur, et mollis turpis tempus. Integer accumsan lacinia suscipit.\"');
INSERT INTO `history_content_items` VALUES (5,5,'Emergence\\CMS\\Item\\Markdown','2017-09-06 19:10:02',23,'2017-09-06 19:37:22',23,NULL,5,23,'Published',1,'\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac dui ultricies, condimentum augue eu, consectetur nulla. Nulla eleifend consectetur nisi, at pretium lorem. Ut porttitor erat quam, ut vestibulum orci consequat ac. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla vehicula eros at odio dictum, id interdum libero malesuada. Morbi consequat erat et eros dapibus tempus. Nulla gravida lectus tellus, vel faucibus odio hendrerit in. Integer non turpis lorem. Donec imperdiet gravida erat, ac sodales odio blandit eu. Morbi ullamcorper vel velit at condimentum. In hac habitasse platea dictumst. Donec eget scelerisque tortor. In congue urna id felis placerat ultrices pellentesque ut libero.\"');
INSERT INTO `history_content_items` VALUES (6,6,'Emergence\\CMS\\Item\\Markdown','2017-09-06 19:20:23',2,'2017-09-06 19:38:38',2,NULL,6,2,'Published',1,'\"Maecenas neque diam, dignissim id nunc id, aliquam lobortis lorem. Nunc porttitor risus non ligula condimentum consectetur. Integer eget tortor fermentum, auctor metus sed, faucibus nisl. Vestibulum fermentum molestie quam, non viverra mi efficitur ac. Curabitur et vehicula leo. Duis lacus odio, tincidunt vel consectetur vel, porttitor ac diam. Sed in laoreet augue, id sodales dui. Praesent quis condimentum metus. Quisque odio nulla, sodales sit amet nisl id, ultrices porttitor nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\\n\\nPellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque eget lacus efficitur, feugiat risus nec, efficitur mi. Morbi iaculis dui ut nunc gravida, eget pretium ipsum cursus. Donec malesuada enim eros, nec vehicula mi cursus ut. Aliquam laoreet nisi id ante facilisis gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed eget odio a neque consectetur pretium eget at sapien. Nunc vel ornare metus. Suspendisse quam leo, finibus quis placerat et, accumsan eu turpis. Suspendisse non aliquet urna.\"');
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

